version: '3' # Specify the version of Docker Compose
services:
# Define the Airflow webserver service
  airflow_webserver:
 # Build the Docker image using the Dockerfile in the current directory
   build:
   # Use the current directory as the build
     context: .
     # Specify the Dockerfile to use for the build
     dockerfile: Dockerfile
   
   ports:
     - "8070:8080"  # Map the container port 8080 to the host port 8070
   # Define the command to run when the container starts
   entrypoint: ./entrypoint.sh